disabled_rules:
  - trailing_whitespace
  - todo
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

excluded:
  - ThirdParty
  - DerivedData
  - build
  - EvilStoreTests/Fixtures

identifier_name:
  min_length: 1
  excluded:
    - id
    - x
    - y
    - to

type_name:
  min_length: 3
  max_length: 60

function_body_length:
  warning: 60
  error: 120

type_body_length:
  warning: 400
  error: 600

cyclomatic_complexity:
  warning: 12
  error: 20

opening_brace:
  ignore_multiline_function_signatures: true
